import sys

print()
# print(sys.path.__str__)
print(f"sys.api_version: {sys.api_version}")
print(f"sys.abiflags: {sys.abiflags}")
print(f"sys.argv: {sys.argv}")
print(f"sys.base_prefix: {sys.base_prefix}")
print(f"sys.builtin_module_names: {sys.builtin_module_names}")
print(f"sys.version_info: {sys.version_info}")
print(f"sys.version: {sys.version}")
print(f"sys.call_tracing: {sys.call_tracing}")
print(f"sys.exc_info: {sys.exc_info}")
# print(f"sys._ExitCode: {sys._ExitCode}")
# print(f"sys.last_exc: {sys.last_exc}")
print(f"sys.float_info: {sys.float_info}")
print(f"sys.__name__: {sys.__name__}")
print(f"sys.get_int_max_str_digits: {sys.get_int_max_str_digits()}")
print(f"sys.getprofile: {sys.getprofile()}")
print(f"sys.get_coroutine_origin_tracking_depth: {sys.get_coroutine_origin_tracking_depth()}")
print(f"sys.getdefaultencoding: {sys.getdefaultencoding()}")
print(f"sys.gettrace: {sys.gettrace()}")
print(f"sys.getunicodeinternedsize: {sys.getunicodeinternedsize()}")
print()